#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jul  9 12:57:58 2019

@author: andres
"""

import glob
import pandas as pd
import numpy as np

a=glob.glob('borja_2019_tus/[1-9]*')

df=pd.DataFrame(columns=['linea', 'ano', 'mes', 'dia_semana', 'tiempo_viaje_medio',
       'tiempo_viaje_desv_estandar', 'tiempo_viaje_desv_tipica','direccion'])
for file in a:
    direccion='puerto_chico'
    if "valdecilla" in file:
        direccion='valdecilla'
    df2=pd.read_csv(file)
    df2['direccion']=direccion
    df=df.append(df2,ignore_index=True)
    df=df[df.ano >0]
    df.to_excel('regularidad_TIEMPO_VIAJE.xlsx')